jobs:
  - job: ubuntu18
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: |
        sudo apt update
        sudo apt install -y software-properties-common
        # sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install cmake build-essential -y
        sudo apt install gcc-8 g++-8 -y
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
        sudo apt install bison autoconf automake -y
        sudo apt install libpng-dev -y
        sudo apt install libjpeg-dev -y
        sudo apt install libgif-dev libfreetype6-dev -y
        sudo apt install freeglut3-dev -y
        sudo apt install liblua5.2-dev libluabind-dev libcpptest-dev -y
        sudo apt install libogg-dev libvorbis-dev libopenal-dev -y
        sudo apt install libavcodec-dev libavformat-dev libavdevice-dev libswscale-dev libpostproc-dev -y
        sudo apt install libmysqlclient-dev -y
        sudo apt install libxml2-dev -y
        sudo apt install libcurl4-openssl-dev libssl-dev -y
        sudo apt install libsquish-dev -y
        sudo apt install liblzma-dev -y
        sudo apt install libgsf-1-dev -y
        sudo apt install qtbase5-dev qttools5-dev qttools5-dev-tools
      displayName: 'Dependencies'
    - script: |
        mkdir build
        cmake --version
        cd build
        cmake -DWITH_STATIC=ON -DWITH_NEL_TESTS=OFF -DWITH_NEL_SAMPLES=ON -DWITH_LUA51=OFF -DWITH_LUA52=ON -DWITH_RYZOM=ON -DWITH_RYZOM_SERVER=ON -DWITH_RYZOM_CLIENT=ON -DWITH_RYZOM_TOOLS=ON -DWITH_NEL_TOOLS=ON -DWITH_NELNS=ON -DWITH_NELNS_LOGIN_SYSTEM=ON -DWITH_NELNS_SERVER=ON -DWITH_QT5=ON -DWITH_LIBGSF=ON ..
        cat CMakeCache.txt
      displayName: 'CMake'
    - script: |
        cd build
        make -j`nproc`
      displayName: 'Make'
  - job: ubuntu20
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - script: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo apt update
        sudo apt install cmake build-essential -y
        sudo apt install bison autoconf automake -y
        sudo apt install libpng-dev -y
        sudo apt install libjpeg-dev -y
        sudo apt install libgif-dev libfreetype6-dev -y
        sudo apt install freeglut3-dev -y
        sudo apt install liblua5.2-dev libluabind-dev libcpptest-dev -y
        sudo apt install libogg-dev libvorbis-dev libopenal-dev -y
        sudo apt install libavcodec-dev libavformat-dev libavdevice-dev libswscale-dev libpostproc-dev -y
        sudo apt install libmysqlclient-dev -y
        sudo apt install libxml2-dev -y
        sudo apt install libcurl4-openssl-dev libssl-dev -y
        sudo apt install libsquish-dev -y
        sudo apt install liblzma-dev -y
        sudo apt install libgsf-1-dev -y
        sudo apt install qtbase5-dev qttools5-dev qttools5-dev-tools
      displayName: 'Dependencies'
    - script: |
        mkdir build
        cmake --version
        cd build
        cmake -DWITH_STATIC=ON -DWITH_NEL_TESTS=OFF -DWITH_NEL_SAMPLES=ON -DWITH_LUA51=OFF -DWITH_LUA52=ON -DWITH_RYZOM=ON -DWITH_RYZOM_SERVER=ON -DWITH_RYZOM_CLIENT=ON -DWITH_RYZOM_TOOLS=ON -DWITH_NEL_TOOLS=ON -DWITH_NELNS=ON -DWITH_NELNS_LOGIN_SYSTEM=ON -DWITH_NELNS_SERVER=ON -DWITH_QT5=ON -DWITH_LIBGSF=ON ..
        cat CMakeCache.txt
      displayName: 'CMake'
    - script: |
        cd build
        make -j`nproc`
      displayName: 'Make'
  - job: windows2019
    timeoutInMinutes: 120
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: self
      fetchDepth: 1
    - task: Cache@2
      inputs:
        key: 'hunter-win2019-x64-rel'
        path: "c:/.hunter/_Base/Cache"
    - task: CMake@1
      inputs:
        workingDirectory: build.release
        cmakeArgs: '-DCMAKE_CONFIGURATION_TYPES=Release -DHUNTER_ENABLED=ON -DHUNTER_CONFIGURATION_TYPES=Release -DFINAL_VERSION=OFF -DWITH_NEL_TESTS=OFF -DWITH_NEL_SAMPLES=OFF -DWITH_NEL_TOOLS=OFF -DWITH_RYZOM_TOOLS=OFF -DWITH_RYZOM_SERVER=OFF -DWITH_RYZOM_CLIENT=ON -DWITH_DRIVER_OPENGL=ON -DWITH_DRIVER_OPENAL=ON -DWITH_DRIVER_DIRECT3D=OFF -DWITH_DRIVER_XAUDIO2=OFF ..'
    - task: MSBuild@1
      inputs:
        solution: build.release/ALL_BUILD.vcxproj
        maximumCpuCount: true
        configuration: release
        platform: 'x64'
